import { Product } from '../types';

export const CATEGORIES: string[] = ['All', 'Ranks', 'Rank Upgrades', 'Keys'];

export const PRODUCTS: Product[] = [
  // RANKS
  {
    id: 'rank-mvp',
    tebexPackageId: 7629191,
    icon: 'mvp',
    name: 'MVP',
    image: '/assets/images/ranks/mvp.png',
    description: 'Light blue gradient prefix, 4 compressed kill tokens daily and 1x Space Key daily.',
    price: 4.99,
    category: 'Ranks',
    perks: [
      'Light Blue Gradient Prefix',
      'All VIP Perks',
      '4 Compressed Kill Tokens Daily',
      '1x Space Key Daily',
      'MVP Kit at /kit (1h cooldown)',
    ],
    color: 'from-indigo-400 to-indigo-800',
  },
  {
    id: 'rank-altar',
    tebexPackageId: 7629189,
    icon: 'altar',
    name: 'ALTAR',
    image: '/assets/images/ranks/altar.png',
    description: 'Exclusive gradient prefix, all MVP perks, daily kill tokens and the Altar kit.',
    price: 7.99,
    category: 'Ranks',
    perks: [
      'All MVP Perks',
      'Exclusive Gradient Chat/Tab Prefix',
      'More Compressed Kill Tokens Daily',
      '1x Space Key Daily',
      'Altar Kit: Bone Blade, Cutlass, Custom Trims (2h cooldown)',
    ],
    color: 'from-blue-400 to-blue-800',
  },
  {
    id: 'rank-altar-plus',
    tebexPackageId: 7629184,
    icon: 'altar-plus',
    name: 'ALTAR+',
    image: '/assets/images/ranks/altar-plus.png',
    description: 'All MVP + VIP perks, 2x Space Keys daily and the exclusive Altar+ kit.',
    price: 13.99,
    category: 'Ranks',
    perks: [
      'All MVP & VIP Perks',
      'More Daily Kill Tokens than Altar',
      '2x Space Keys Daily',
      'Altar+ Kit: Night Piercer, Frost Scythe (3h cooldown)',
    ],
    color: 'from-violet-400 to-violet-800',
    isPopular: true,
  },
  {
    id: 'rank-custom',
    tebexPackageId: 7629180,
    icon: 'custom-rank',
    name: 'CUSTOM RANK',
    image: '/assets/images/ranks/custom-rank.png',
    description: 'All Altar+ perks plus /setprefix, your own kit and a daily custom key.',
    price: 19.99,
    category: 'Ranks',
    perks: [
      'All Altar / Altar+ / VIP Perks',
      '/setprefix — Custom Named Prefix',
      'Your Own Premade Kit (5h cooldown)',
      '1x Space Key + 1 Custom Key Daily',
      'Gift the Server a Space Key (/keyall)',
      'Shadow Blade & Nightpiercer Kit',
    ],
    color: 'from-pink-400 to-rose-800',
  },
  // RANK UPGRADES
  {
    id: 'upgrade-mvp-altar',
    tebexPackageId: 7518069,
    icon: 'upgrade-mvp-altar',
    name: 'MVP → ALTAR',
    description: 'If you have MVP you can upgrade to Altar — otherwise it will not work.',
    price: 3.99,
    category: 'Rank Upgrades',
    color: 'from-indigo-400 to-pink-600',
  },
  {
    id: 'upgrade-altar-plus',
    tebexPackageId: 7518811,
    icon: 'upgrade-altar-plus',
    name: 'ALTAR → ALTAR+',
    description: 'If you have Altar you can upgrade to Altar+ — if you dont have Altar this wont work.',
    price: 5.5,
    category: 'Rank Upgrades',
    color: 'from-indigo-400 to-pink-600',
  },
  {
    id: 'upgrade-custom',
    tebexPackageId: 7528722,
    icon: 'upgrade-custom',
    name: 'ALTAR+ → CUSTOM',
    description: 'If you have Altar+ you can upgrade it to Custom — otherwise it will not work.',
    price: 5.25,
    category: 'Rank Upgrades',
    color: 'from-indigo-400 to-pink-600',
  },
  // KEYS
  {
    id: 'key-koth',
    tebexPackageId: 7501293,
    icon: 'key-koth',
    name: 'KOTH KEY',
    image: '/assets/images/keys/koth-key.png',
    description: 'When buying, receive 3 koth keys ingame.',
    price: 9.99,
    category: 'Keys',
    perks: ['3x KOTH Keys', 'Open the KOTH crate', 'Chance at one-of-a-kind loot'],
    color: 'from-red-500 to-rose-700',
  },
  {
    id: 'key-custom',
    tebexPackageId: 7543620,
    icon: 'key-custom',
    name: 'CUSTOM KEY',
    image: '/assets/images/keys/custom-key.png',
    description: 'When you buy this you get 1 wisdom key ingame.',
    price: 3.0,
    category: 'Keys',
    perks: ['1x Custom (wisdom) Key', 'Open the Custom crate'],
    color: 'from-blue-400 to-indigo-800',
  },
  {
    id: 'key-pumpkin',
    tebexPackageId: 1000007,
    icon: 'key-pumpkin',
    name: 'PUMPKIN KEY',
    image: '/assets/images/keys/pumpkin-key.png',
    description: 'Unlocks the Pumpkin crate — seasonal Halloween drops.',
    price: 4.99,
    category: 'Keys',
    perks: ['Seasonal Halloween Loot', 'Spooky Cosmetics', 'Coins Bonus'],
    color: 'from-orange-500 to-orange-800',
  },
  {
    id: 'key-undead',
    tebexPackageId: 1000008,
    icon: 'key-undead',
    name: 'UNDEAD KEY',
    image: '/assets/images/keys/undead-key.png',
    description: 'Unlocks the Undead crate — cursed loot and dark cosmetics.',
    price: 12.99,
    category: 'Keys',
    perks: ['Cursed Loot Pool', 'Dark Cosmetics', 'Rare Pet Drops'],
    color: 'from-lime-500 to-green-800',
  },
];
