import { Product } from '../types';

export const CATEGORIES: string[] = ['All', 'Ranks', 'Rank Upgrades', 'Keys'];

export const PRODUCTS: Product[] = [
  // RANKS
  {
    id: 'rank-mvp',
    tebexPackageId: 7629191,
    icon: 'mvp',
    name: 'MVP',
    image: '/assets/images/ranks/mvp.png',
    description: 'Light blue gradient prefix, 4 compressed kill tokens daily and 1x Space Key daily.',
    price: 6,
    category: 'Ranks',
    perks: [
      'Light Blue Gradient Prefix',
      'All VIP Perks',
      '4 Compressed Kill Tokens Daily',
      '1x Space Key Daily',
      'MVP Kit at /kit (1h cooldown)',
    ],
    color: 'from-indigo-400 to-indigo-800',
  },
  {
    id: 'rank-altar',
    tebexPackageId: 7629189,
    icon: 'altar',
    name: 'ALTAR',
    image: '/assets/images/ranks/altar.png',
    description: 'Exclusive gradient prefix, all MVP perks, daily kill tokens and the Altar kit.',
    price: 9,
    category: 'Ranks',
    perks: [
      'All MVP Perks',
      'Exclusive Gradient Chat/Tab Prefix',
      'More Compressed Kill Tokens Daily',
      '1x Space Key Daily',
      'Altar Kit: Bone Blade, Cutlass, Custom Trims (2h cooldown)',
    ],
    color: 'from-blue-400 to-blue-800',
  },
  {
    id: 'rank-altar-plus',
    tebexPackageId: 7629184,
    icon: 'altar-plus',
    name: 'ALTAR+',
    image: '/assets/images/ranks/altar-plus.png',
    description: 'All MVP + VIP perks, 2x Space Keys daily and the exclusive Altar+ kit.',
    price: 16,
    category: 'Ranks',
    perks: [
      'All MVP & VIP Perks',
      'More Daily Kill Tokens than Altar',
      '2x Space Keys Daily',
      'Altar+ Kit: Night Piercer, Frost Scythe (3h cooldown)',
    ],
    color: 'from-violet-400 to-violet-800',
    isPopular: true,
  },
  {
    id: 'rank-early-access',
    icon: 'early-access',
    name: 'EARLY ACCESS',
    description: 'Join the first wave — an exclusive limited rank with permanent perks and priority queue.',
    price: 32,
    category: 'Ranks',
    perks: [
      'Exclusive Early Access Chat/Tab Tag',
      'Priority Queue Access',
      'Early Access to New Features',
      'Exclusive Early Access Kit',
      'All MVP Perks',
    ],
    color: 'from-teal-400 to-teal-800',
  },
  // RANK UPGRADES
  {
    id: 'upgrade-mvp-altar',
    tebexPackageId: 7518069,
    icon: 'upgrade-mvp-altar',
    name: 'MVP → ALTAR',
    description: 'If you have MVP you can upgrade to Altar — otherwise it will not work.',
    price: 3.99,
    category: 'Rank Upgrades',
    color: 'from-indigo-400 to-pink-600',
  },
  {
    id: 'upgrade-altar-plus',
    tebexPackageId: 7518811,
    icon: 'upgrade-altar-plus',
    name: 'ALTAR → ALTAR+',
    description: 'If you have Altar you can upgrade to Altar+ — if you dont have Altar this wont work.',
    price: 5.5,
    category: 'Rank Upgrades',
    color: 'from-indigo-400 to-pink-600',
  },
  {
    id: 'upgrade-custom',
    tebexPackageId: 7528722,
    icon: 'upgrade-custom',
    name: 'ALTAR+ → CUSTOM',
    description: 'If you have Altar+ you can upgrade it to Custom — otherwise it will not work.',
    price: 5.25,
    category: 'Rank Upgrades',
    color: 'from-indigo-400 to-pink-600',
  },
  // KEYS
  {
    id: 'key-spooky',
    icon: 'key-spooky',
    name: 'SPOOKY KEY',
    description: 'Unlocks the Spooky crate — Halloween loot, cosmetics and bonus coins.',
    price: 5,
    priceTiers: [
      { label: '1x', price: 5, tebexPackageId: 7543620 },
      { label: '3x', price: 12, tebexPackageId: 7543621 },
      { label: '5x', price: 17, tebexPackageId: 7543625 },
      { label: '10x', price: 27, tebexPackageId: 7501293 },
    ],
    category: 'Keys',
    perks: ['Seasonal Spooky Loot', 'Exclusive Cosmetics', 'Bonus Coins'],
    color: 'from-purple-500 to-fuchsia-800',
  },
  {
    id: 'key-undead',
    icon: 'key-undead',
    name: 'UNDEAD KEY',
    image: '/assets/images/keys/undead-key.png',
    description: 'Unlocks the Undead crate — cursed loot and dark cosmetics.',
    price: 2,
    priceTiers: [
      { label: '1x', price: 2, tebexPackageId: 7727214 },
      { label: '3x', price: 6, tebexPackageId: 7727222 },
      { label: '5x', price: 10, tebexPackageId: 7727226 },
      { label: '10x', price: 15, tebexPackageId: 7727231 },
    ],
    category: 'Keys',
    perks: ['Cursed Loot Pool', 'Dark Cosmetics', 'Rare Pet Drops'],
    color: 'from-lime-500 to-green-800',
  },
  {
    id: 'key-pumpkin',
    icon: 'key-pumpkin',
    name: 'PUMPKIN KEY',
    image: '/assets/images/keys/pumpkin-key.png',
    description: 'Unlocks the Pumpkin crate — seasonal Halloween drops.',
    price: 4,
    priceTiers: [
      { label: '1x', price: 4, tebexPackageId: 7727234 },
      { label: '3x', price: 11, tebexPackageId: 7727237 },
      { label: '5x', price: 16, tebexPackageId: 7727239 },
      { label: '10x', price: 22, tebexPackageId: 7727243 },
    ],
    category: 'Keys',
    perks: ['Seasonal Halloween Loot', 'Spooky Cosmetics', 'Coins Bonus'],
    color: 'from-orange-500 to-orange-800',
  },
  {
    id: 'key-ghost',
    icon: 'key-ghost',
    name: 'GHOST KEY',
    description: 'Unlocks the Ghost crate — spectral loot and phantom cosmetics.',
    price: 3,
    priceTiers: [
      { label: '1x', price: 3, tebexPackageId: 7727245 },
      { label: '3x', price: 8, tebexPackageId: 7727246 },
      { label: '5x', price: 13, tebexPackageId: 7727252 },
      { label: '10x', price: 18, tebexPackageId: 7727253 },
    ],
    category: 'Keys',
    perks: ['Spectral Loot Pool', 'Phantom Cosmetics', 'Chance at Rare Pets'],
    color: 'from-sky-400 to-indigo-800',
  },
  {
    id: 'key-soul',
    icon: 'key-soul',
    name: 'SOUL KEY',
    description: 'Unlocks the Soul crate — ethereal loot and soul-forged cosmetics.',
    price: 3,
    priceTiers: [
      { label: '1x', price: 3, tebexPackageId: 7727258 },
      { label: '3x', price: 8, tebexPackageId: 7727259 },
      { label: '5x', price: 13, tebexPackageId: 7727262 },
    ],
    category: 'Keys',
    perks: ['Ethereal Loot Pool', 'Soul-Forged Cosmetics', 'Rare Drops'],
    color: 'from-rose-500 to-red-800',
  },
];
